name: Publish to PyPI and Docker Hub

on:
 release:
  types:
   - created

 docker-image-CI:
   name: Docker Image CI
   runs-on: ubuntu-latest
   steps:

    - name: Check out git repository
      uses: actions/checkout@v3

    - name: Publish main image (Dockerfile) to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: clinicalgenomics/schug
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ github.event.release.tag_name }}"
